[package]
name = "equate"
version = "0.2.1"
entrypoint = "src/lib.typ"
compiler = "0.11.0"
authors = ["Eric Biedert"]
repository = "https://github.com/EpicEricEE/typst-equate"
license = "MIT"
description = "Various enhancements for mathematical expressions."
exclude = ["README.md", "assets", "tests"]
categories = ["layout", "model"]
keywords = [
  "math", "equation", "formula", "sub", "number", "numbering", "align",
  "interrupt", "intertext", "multiline", "multi-line", "split", "break"
]
